In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a.shape

(5,)

In [5]:
b = np.array([[1,2,3,4], [5,6,7,8]])

In [6]:
b.shape

(2, 4)

In [7]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [8]:
new_arr = c.reshape(4,3)

In [9]:
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
c.shape

(12,)

In [11]:
new_arr.shape

(4, 3)

In [12]:
new_arr2 = c.reshape(2,3,2)

In [13]:
new_arr2.shape

(2, 3, 2)

In [14]:
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [15]:
new_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
flattened_arr = new_arr.reshape(-1)

In [17]:
flattened_arr.shape

(12,)